
import Foundation

public enum NonTerminal: String, Equatable, CustomStringConvertible {

    public var description: String {
        return rawValue
    }

    case Definitions = "Definitions"
    case Definition = "Definition"
    case ArgumentNameKeyword = "ArgumentNameKeyword"
    case CallbackOrInterfaceOrMixin = "CallbackOrInterfaceOrMixin"
    case InterfaceOrMixin = "InterfaceOrMixin"
    case InterfaceRest = "InterfaceRest"
    case Partial = "Partial"
    case PartialDefinition = "PartialDefinition"
    case PartialInterfaceOrPartialMixin = "PartialInterfaceOrPartialMixin"
    case PartialInterfaceRest = "PartialInterfaceRest"
    case InterfaceMembers = "InterfaceMembers"
    case InterfaceMember = "InterfaceMember"
    case PartialInterfaceMembers = "PartialInterfaceMembers"
    case PartialInterfaceMember = "PartialIntrerfaceMember"
    case Inheritance = "Inheritance"
    case MixinRest = "MixinRest"
    case MixinMembers = "MixinMembers"
    case MixinMember = "MixinMember"
    case IncludesStatement = "IncludesStatement"
    case CallbackRestOrInterface = "CallbackRestOrInterface"
    case CallbackInterfaceMembers = "CallbackInterfaceMembers"
    case CallbackInterfaceMember = "CallbackInterfaceMember"
    case Const = "Const"
    case ConstValue = "ConstValue"
    case BooleanLiteral = "BooleanLiteral"
    case FloatLiteral = "FloatLiteral"
    case ConstType = "ConstType"
    case ReadOnlyMember = "ReadOnlyMember"
    case ReadOnlyMemberRest = "ReadOnlyMemberRest"
    case ReadWriteAttribute = "ReadWriteAttribute"
    case AttributeRest = "AttributeRest"
    case AttributeName = "AttributeName"
    case AttributeNameKeyword = "AttributeNameKeyword"
    case ReadOnly = "ReadOnly"
    case DefaultValue = "DefaultValue"
    case Operation = "Operation"
    case RegularOperation = "RegularOperation"
    case SpecialOperation = "SpecialOperation"
    case Special = "Special"
    case OperationRest = "OperationRest"
    case OptionalOperationName = "OptionalOperationName"
    case OperationName = "OperationName"
    case OperationNameKeyword = "OperationNameKeyword"
    case ArgumentList = "ArgumentList"
    case Arguments = "Arguments"
    case Argument = "Argument"
    case ArgumentRest = "ArgumentRest"
    case ArgumentName = "ArgumentName"
    case Ellipsis = "Ellipsis"
    case ReturnType = "ReturnType"
    case Constructor = "Constructor"
    case Stringifier = "Stringifier"
    case StringifierRest = "StringifierRest"
    case StaticMember = "StaticMember"
    case StaticMemberRest = "StaticMemberRest"
    case Iterable = "Iterable"
    case OptionalType = "OptionalType"
    case AsyncIterable = "AsyncIterable"
    case ReadWriteMaplike = "ReadWriteMaplike"
    case MaplikeRest = "MaplikeRest"
    case ReadWriteSetlike = "ReadWriteSetlike"
    case SetlikeRest = "SetlikeRest"
    case Namespace = "Namespace"
    case NamespaceMembers = "NamespaceMembers"
    case NamespaceMember = "NamespaceMember"
    case Dictionary = "Dictionary"
    case DictionaryMembers = "DictionaryMembers"
    case DictionaryMember = "DictionaryMember"
    case DictionaryMemberRest = "DictionaryMemberRest"
    case PartialDictionary = "PartialDictionary"
    case Default = "Default"
    case Enum = "Enum"
    case EnumValueList = "EnumValueList"
    case EnumValueListComma = "EnumValueListComma"
    case EnumValueListString = "EnumValueListString"
    case CallbackRest = "CallbackRest"
    case Typedef = "Typedef"
    case `Type` = "`Type`"
    case TypeWithExtendedAttributes = "TypeWithExtendedAttributes"
    case SingleType = "SingleType"
    case UnionType = "UnionType"
    case UnionMemberType = "UnionMemberType"
    case UnionMemberTypes = "UnionMemberTypes"
    case DistinguishableType = "DistinguishableType"
    case PrimitiveType = "PrimitiveType"
    case UnrestrictedFloatType = "UnrestrictedFloatType"
    case FloatType = "FloatType"
    case UnsignedIntegerType = "UnsignedIntegerType"
    case IntegerType = "IntegerType"
    case OptionalLong = "OptionalLong"
    case StringType = "StringType"
    case PromiseType = "PromiseType"
    case RecordType = "RecordType"
    case Null = "Null"
    case BufferRelatedType = "BufferRelatedType"
    case ExtendedAttributeList = "ExtendedAttributeList"
    case ExtendedAttributes = "ExtendedAttributes"
    case ExtendedAttribute = "ExtendedAttribute"
    case ExtendedAttributeRest = "ExtendedAttributeRest"
    case ExtendedAttributeInner = "ExtendedAttributeInner"
    case Other = "Other"
    case OtherOrComma = "OtherOrComma"
    case IdentifierList = "IdentifierList"
    case Identifiers = "Identifiers"
    case ExtendedAttributeNoArgs = "ExtendedAttributeNoArgs"
    case ExtendedAttributeArgList = "ExtendedAttributeArgList"
    case ExtendedAttributeIdent = "ExtendedAttributeIdent"
    case ExtendedAttributeIdentList = "ExtendedAttributeIdentList"
    case ExtendedAttributeNamedArgList = "ExtendedAttributeNamedArgList"
}

public enum Terminal: String, Equatable, CustomStringConvertible {

    public var description: String {
        return rawValue
    }

    case openingParenthesis = "("
    case closingParenthesis = ")"
    case openingCurlyBraces = "{"
    case closingCurlyBraces = "}"
    case openingSquareBracket = "["
    case closingSquareBracket = "]"
    case openingAngleBracket = "<"
    case closingAngleBracket = ">"
    case async = "async"
    case attribute = "attribute"
    case callback = "callback"
    case const = "const"
    case constructor = "constructor"
    case deleter = "deleter"
    case dictionary = "dictionary"
    case `enum` = "enum"
    case getter = "getter"
    case includes = "includes"
    case inherit = "inherit"
    case interface = "interface"
    case iterable = "iterable"
    case maplike = "maplike"
    case mixin = "mixin"
    case namespace = "namespace"
    case partial = "partial"
    case readonly = "readonly"
    case required = "required"
    case setlike = "setlike"
    case setter = "setter"
    case `static` = "static"
    case stringifier = "stringifier"
    case typedef = "typedef"
    case unrestricted = "unrestricted"
    case semicolon = ";"
    case colon = ":"
    case equalSign = "="
    case comma = ","
    case questionMark = "?"
    case dot = "."
    case ellipsis = "..."
    case minus = "-"

    case `true` = "true"
    case `false` = "false"

    case negativeInfinity = "-Infinity"
    case infinity = "Infinity"
    case nan = "NaN"

    case null = "null"
    case record = "record"
    case promise = "Promise"
    case sequence = "sequence"
    case object = "object"
    case symbol = "symbol"
    case or = "or"
    case any = "any"
    case optional = "optional"

    case ByteString = "ByteString"
    case DOMString = "DOMString"
    case USVString = "USVString"

    case boolean = "boolean"
    case byte = "byte"
    case octet = "octet"
    case float = "float"
    case double = "double"
    case unsigned = "unsigned"
    case short = "short"
    case long = "long"
    case void = "void"

    case ArrayBuffer = "ArrayBuffer"
    case DataView = "DataView"
    case Int8Array = "Int8Array"
    case Int16Array = "Int16Array"
    case Int32Array = "Int32Array"
    case Uint8Array = "Uint8Array"
    case Uint16Array = "Uint16Array"
    case Uint32Array = "Uint32Array"
    case Uint8ClampedArray = "Uint8ClampedArray"
    case Float32Array = "Float32Array"
    case Float64Array = "Float64Array"
    case FrozenArray = "FrozenArray"
}
