name: Build and Test

on:
  push:
    branches: [ develop, release ]
  pull_request:
    branches: [ develop, release ]

jobs:
  build:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - name: Select Xcode 13.2.1
      run: sudo xcode-select -s /Applications/Xcode_13.2.1.app/Contents/Developer
    - name: Xcode version check
      run: xcodebuild -version
    - name: Check version
      run: swift --version
    - name: Build
      run: swift build -v
    - name: Test
      run: swift test -v
