name: Build and Test

on:
  push:
    branches: [ develop, release ]
  pull_request:
    branches: [ develop, release ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        swift-version: "5.2.0"
    - name: Xcode 11.5
      run: sudo xcode-select -s /Applications/Xcode_11.5.app/Contents/Developer
    - name: Xcode version check
      run: xcodebuild -version
    - name: Check version
      run: swift --version
    - name: Build
      run: swift build -v
    - name: Test
      run: swift test -v
